INSERT INTO Pokemon(nome, imagem) VALUES("Pikachu", "/View/Modules/Pokephone/Images/Pokemons/Pikachu.png"), 
("Bulbassauro", "/View/Modules/Pokephone/Images/Pokemons/Bulbassauro.png"),
("Charmander", "/View/Modules/Pokephone/Images/Pokemons/Charmander.png"),
("Squirtle", "/View/Modules/Pokephone/Images/Pokemons/Squirtle.png"),
("Butterfree", "/View/Modules/Pokephone/Images/Pokemons/Butterfree.png"),
("Eevee", "/View/Modules/Pokephone/Images/Pokemons/Eevee.png"),
("Onix", "/View/Modules/Pokephone/Images/Pokemons/Onix.png"),
("Flareon", "/View/Modules/Pokephone/Images/Pokemons/Flareon.png"),
("Ekans", "/View/Modules/Pokephone/Images/Pokemons/Ekans.png"),
("Caterpie", "/View/Modules/Pokephone/Images/Pokemons/Caterpie.png"),
("Pidgey", "/View/Modules/Pokephone/Images/Pokemons/Pidgey.png"),
("Rattata", "/View/Modules/Pokephone/Images/Pokemons/Rattata.png"),
("Meowth", "/View/Modules/Pokephone/Images/Pokemons/Meowth.png"),
("Jigglypuff", "/View/Modules/Pokephone/Images/Pokemons/Jigglypuff.png"),
("Vulpix", "/View/Modules/Pokephone/Images/Pokemons/Vulpix.png"),
("Sandshrew", "/View/Modules/Pokephone/Images/Pokemons/Sandshrew.png"),
("Spearow", "/View/Modules/Pokephone/Images/Pokemons/Spearow.png");